-- Generated by nwg-displays on 2026-07-06 at 19:50:29. Do not edit manually.

hl.workspace_rule({
    workspace = "6",
    monitor = "DP-1",
    default = true
})
hl.workspace_rule({
    workspace = "7",
    monitor = "DP-1"
})
hl.workspace_rule({
    workspace = "8",
    monitor = "DP-1"
})
hl.workspace_rule({
    workspace = "9",
    monitor = "DP-1"
})
hl.workspace_rule({
    workspace = "10",
    monitor = "DP-1"
})
